services:
  db: 
    image: mariadb:latest 
    environment:
      MARIADB_ROOT_PASSWORD: ${ROOT_PASSWORD} 
    mem_limit: 512m 

  web: 
    build: . 
    ports:
      - "8096:80"
    environment:
      ROOT_PASSWORD: ${ROOT_PASSWORD}
    security_opt:
      - no-new-privileges:true 
    depends_on:
      - db
